from turtle import *

def main():
    screensize(800, 800)
    bgcolor("skyblue")
    speed(0)
    #title
    penup()
    goto(-150, 250)
    pendown()
    pensize(3)
    pencolor("darkblue")
    write("Winter Wonderland", font=("Arial", 24, "bold"))

    
    #pathwya
    penup()
    goto(-268, -200)
    pendown()
    color("gray")
    begin_fill()
    forward(400)
    left(90)
    forward(50)
    left(90)
    forward(400)
    left(90)
    forward(50)
    left(90)
    end_fill()
    
    #snowman
    penup()
    goto(-150, -150)
    pendown()
    color("white")
    
    # Bottom circle
    begin_fill()
    circle(30)
    end_fill()
    
    # Middle circle
    penup()
    goto(-150, -90)
    pendown()
    begin_fill()
    circle(20)
    end_fill()
    
    #circlehead
    penup()
    goto(-150, -50)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    
    #eyesofthesnomwna
    penup()
    goto(-155, -40)
    dot(5, "black")
    goto(-145, -40)
    dot(5, "black")
    
    #nose
    penup()
    goto(-150, -45)
    pendown()
    pencolor("orange")
    pensize(3)
    forward(10)
    pencolor("black")
    
    #treebottom
    penup()
    goto(100, -150)
    pendown()
    color("saddlebrown")
    begin_fill()
    forward(20)
    left(90)
    forward(40)
    left(90)
    forward(20)
    left(90)
    forward(40)
    left(90)
    end_fill()
    
    #tree1leaves
    penup()
    goto(80, -110)
    pendown()
    color("forestgreen")
    begin_fill()
    forward(60)
    left(120)
    forward(60)
    left(120)
    forward(60)
    left(120)
    end_fill()
    
    #tree2bottom
    penup()
    goto(-250, -150)
    pendown()
    color("saddlebrown")
    begin_fill()
    forward(20)
    left(90)
    forward(40)
    left(90)
    forward(20)
    left(90)
    forward(40)
    left(90)
    end_fill()
    
    #tree2leaves
    penup()
    goto(-270, -110)
    pendown()
    color("forestgreen")
    begin_fill()
    forward(60)
    left(120)
    forward(60)
    left(120)
    forward(60)
    left(120)
    end_fill()
    
    #bottome/baseofthehouse
    penup()
    goto(0, -150)
    pendown()
    color("salmon2")
    begin_fill()
    forward(60)
    left(90)
    forward(60)
    left(90)
    forward(60)
    left(90)
    forward(60)
    left(90)
    end_fill()
    
    #roof
    penup()
    goto(0, -90)
    pendown()
    color("brown")
    begin_fill()
    forward(60)
    left(120)
    forward(60)
    left(120)
    forward(60)
    left(120)
    end_fill()

    #moon
    penup()
    goto(200, 200)
    pendown()
    color("cornsilk1")
    begin_fill()
    circle(50)
    end_fill()

    #star1
    penup()
    goto(-300, 200)
    pendown()
    color("yellow")
    begin_fill()
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    end_fill()

    #star2
    penup()
    goto(-250, 150)
    pendown()
    begin_fill()
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    end_fill()

    #star3
    penup()
    goto(-200, 180)
    pendown()
    begin_fill()
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    end_fill()

    #star4
    penup()
    goto(-100, 220)
    pendown()
    begin_fill()
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    end_fill()

    #star5
    penup()
    goto(0, 200)
    pendown()
    begin_fill()
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    forward(10)
    right(144)
    end_fill()

    
    #happyflyingperson
    penup()
    goto(0, 50)  #position of the flying person
    pendown()
    fillcolor("black")
    pensize(2)

    #body
    pencolor("black")
    setheading(-90)
    forward(50)

    penup()
    goto(-5, 60)
    pendown()
    pensize(3)
    pencolor("darkblue")
    write("OMG IM FLYING!", font=("Comic sans MS", 24, "bold"))

    #head
    penup()
    goto(-5, 50)
    pendown()
    pencolor("black")
    begin_fill()
    circle(5)  #small circle for the head
    end_fill()

    #arms
    penup()
    goto(0, 30)
    pendown()
    pencolor("black")
    setheading(150)
    forward(30)
    penup()
    goto(0, 30)
    pendown()
    setheading(30)
    forward(30)

    #legs
    penup()
    goto(0, 0)
    pendown()
    pencolor("black")
    setheading(210)
    forward(30)
    penup()
    goto(0, 0)
    pendown()
    setheading(330)
    forward(30)
    hideturtle()

main()
