from turtle import *
def main():
    bgcolor("gold")
    screensize(800, 800)
    speed(10)
    pensize(5)
    showturtle()


    
    #head
    penup()
    goto(0,-230)
    pendown()
    pencolor("black")
    fillcolor("white")
    begin_fill()
    setheading(0)
    circle(250)
    end_fill()
    
    #redspotleft
    penup()
    pensize(5)
    goto(-249.7,-50)
    pendown()  
    pencolor("black")
    fillcolor("red")
    begin_fill()
    setheading(0)
    circle(110,180)
    end_fill()

    #redspotright
    penup()
    pensize(5)
    goto(246.7,-50)
    pendown()  
    pencolor("black")
    fillcolor("red")
    begin_fill()
    setheading(0)
    circle(110,-180)
    end_fill()
    
    #middle redspot
    penup()
    goto(0,15)
    pendown()
    pencolor("black")
    pensize(5)
    fillcolor("Red")
    begin_fill()
    setheading(0)
    circle(115)
    end_fill()

    
    #black circle around
    penup()
    goto(-1.5,-253)
    pendown()
    pencolor("black")
    pensize(50)
    fillcolor("")
    begin_fill()
    setheading(0)
    circle(274)
    end_fill()
    

    #face (2 semcicircles for sides)
    #face (rectangle to make oval and also remove pencolor in the middle)    
    penup()
    goto(70,-260)
    pendown()
    pensize(5)
    pencolor("black")
    fillcolor("wheat1")
    begin_fill()
    setheading(0)
    circle(100,180)
    end_fill()

    penup()
    goto(-70,-260)
    pendown()  
    pencolor("black")
    fillcolor("wheat1")
    begin_fill()
    setheading(0)
    circle(100,-180)
    end_fill()

    penup()
    goto(-70,-260)
    pendown()  
    pencolor("black")
    fillcolor("wheat1")
    begin_fill()
    setheading(0)
    forward(140)
    left(90)
    forward(200)
    left(90)
    forward(140)
    left(90)
    forward(200)
    left(90)
    end_fill()

    penup()
    pensize(1)
    goto(-72,-257)
    pendown()  
    pencolor("wheat1")
    fillcolor("wheat1")
    begin_fill()
    setheading(0)
    forward(150)
    left(90)
    forward(193)
    left(90)
    forward(160)
    left(90)
    forward(190)
    left(90)
    end_fill()

    #lefteye(more circles to make into oval)
    penup()
    pensize(5)
    goto(-55,-150)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()
    
    penup()
    pensize(5)
    goto(-55,-155)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(-55,-160)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(-55,-165)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(-55,-170)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(-55,-175)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()
    
    #righteye(more circles to make into oval)
    penup()
    pensize(5)
    goto(55,-150)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()
    
    penup()
    pensize(5)
    goto(55,-155)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(55,-160)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(55,-165)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    penup()
    pensize(5)
    goto(55,-170)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()
    hideturtle()

    penup()
    pensize(5)
    goto(55,-175)
    pendown()
    pencolor("black")
    fillcolor("black")
    begin_fill()
    setheading(0)
    circle(20)
    end_fill()

    #toad
    penup()
    goto(-85,-66)
    pendown()
    pensize(3)
    pencolor("black")
    write("TOAD!", font=("Comic Sans MS", 55, "bold"))

    

main()
